[package]
name = "sakana-module-system"
version.workspace = true
edition.workspace = true

[dependencies]
sakana-protocol.workspace = true
sakana-util-win.workspace = true

[dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Power",
    "Win32_System_Shutdown",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Shell",
]
