[package]
name = "cue"
version = "0.4.9"
edition.workspace = true

[[bin]]
name = "cue"
path = "src/main.rs"

[dependencies]
cue-protocol.workspace = true
cue-core.workspace = true
cue-ui.workspace = true
cue-windows.workspace = true
cue-module-app.workspace = true
cue-module-bookmark.workspace = true
cue-module-file.workspace = true
cue-module-system.workspace = true
futures.workspace = true
gpui.workspace = true

[build-dependencies]
embed-resource = "3"
