[package]
name = "cue-module-system"
version = "0.1.0"
edition.workspace = true

[dependencies]
cue-protocol.workspace = true

[dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Power",
    "Win32_System_Shutdown",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Shell",
]
